name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Profile
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          filename: metrics/profile.svg
          committer_branch: metrics
      - name: Habits
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics/habits.svg
          committer_branch: metrics
          base: ""
          plugin_habits: yes
          plugin_habits_from: 400
          plugin_habits_charts: yes
          plugin_habits_facts: yes
          config_timezone: America/Recife
      - name: Pinned
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/pinned.svg
          committer_branch: metrics
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_repositories: yes
          plugin_repositories_pinned: 6
      - name: Languages
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/languages.svg
          committer_branch: metrics
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_threshold: 5%
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot, scss, sass
          plugin_languages_colors: rainbow
          plugin_languages_limit: 8
          plugin_languages_details: byte-size, percentage, lines
      - name: Isocalendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/isocalendar.svg
          committer_branch: metrics
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
